name:  my-workflow

on:
  [workflow_call]
  
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          echo "${{ vars.dns_value }}"
          tree
